### ISSUE TITLE
ocr

### ISSUE THREAD

**Issue by sudonitin** [globefire/ocr-with-python#1]
```

from PIL import Image
import pytesseract
from pytesseract import image_to_string

im = Image.open("test.png")
print(image_to_string(im))


```

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\Lib\defaulter\TEST.py", line 7, in <module>
    print(image_to_string(im))
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
[Finished in 3.8s]

**Comment by globefire** [comment]
@ EgnaroDev

**Comment by globefire** [comment]
@EgnaroDev

**Comment by globefire** [comment]
@Pethaf
